###
POST http://192.168.49.2/api/v1/initializeTables
Content-Type: application/json

{
  "numberOfTables": 10
}


###
POST http://192.168.49.2/api/v1/reserveTable
Content-Type: application/json

{
  "numberOfCustomers": 3
}




###
POST http://192.168.49.2/api/v1/cancelReservation
Content-Type: application/json

{
  "bookingId": "8ea953c6-03c4-4994-a7f7-27dd2305148d"
}