###
POST http://192.168.49.2/api/v1/initializeTables
Content-Type: application/json

{
  "numberOfTables": 5000
}


###
POST http://192.168.49.2/api/v1/reserveTable
Content-Type: application/json

{
  "numberOfCustomers": 500
}




###
POST http://192.168.49.2/api/v1/cancelReservation
Content-Type: application/json

{
  "bookingId": "c1b5b695-9bbc-41d6-b0db-7036222aa1b7"
}