###
POST http://192.168.49.2/api/v1/initializeTables
Content-Type: application/json

{
  "numberOfTables": 2
}


###
POST http://192.168.49.2/api/v1/reserveTable
Content-Type: application/json

{
  "numberOfCustomers": 3
}




###
POST http://192.168.49.2/api/v1/cancelReservation
Content-Type: application/json

{
  "bookingId": "ce104766-99e4-4b76-b7bf-5663c424a0ad"
}