###
POST http://localhost:8080/api/v1/initializeTables
Content-Type: application/json

{
  "numberOfTables": 2
}


###
POST http://localhost:8080/api/v1/reserveTable
Content-Type: application/json

{
  "numberOfCustomers": 3
}




###
POST http://localhost:8080/api/v1/cancelReservation
Content-Type: application/json

{
  "bookingId": "943ea226-4d41-4afe-bf2b-ca6d8ed0a38a"
}