###
POST http://localhost:8080/api/v1/initializeTables
Content-Type: application/json

{
  "numberOfTables": 10
}


###
POST http://localhost:8080/api/v1/reserveTable
Content-Type: application/json

{
  "numberOfCustomers": 2
}




###
POST http://localhost:8080/api/v1/cancelReservation
Content-Type: application/json

{
  "bookingId": "81069b06-4e34-4d94-96f4-78fc719c93cc"
}