openapi: 3.0.3
info:
  title: Restaurant Table Reservation API
  description: This API allows for managing table reservations in a restaurant.
  version: 1.0-SNAPSHOT
servers:
  - url: http://localhost/api/v1
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
        message:
          type: string
          description: Error message
    InitializeTablesDTO:
      type: object
      properties:
        numberOfTables:
          type: number
    ReserveTableDTO:
      type: object
      properties:
        numberOfCustomers:
          type: number
    ReserveTableResponse:
      type: object
      properties:
        bookingId:
          type: string
          format: uuid
        bookedTables:
          type: number
        remainingTables:
          type: number
    CancelReservationDTO:
      type: object
      properties:
        bookingId:
          type: string
          format: uuid
    CancelReservationResponse:
      type: object
      properties:
        freedTables:
          type: number
        remainingTables:
          type: number

  responses:
    NotEnoughTablesForAllCustomersException:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BookingIDNotFoundException:
      description: Resource Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    TablesAlreadyInitializedException:
      description: Tables already initialized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    TablesNotInitializedException:
      description: Tables not initialized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NoContent:
      description: No Content
      content:
        application/json:
          schema: {}  # Empty schema for 204 No Content
paths:
  /initializeTables:
    post:
      summary: Initialize Tables
      description: |
        The `initializeTables` API initializes all tables in the restaurant.

        - This API must be called first and only once at the beginning.
        - The number of tables to initialize must be provided in the request body.
        - Returns success if tables are initialized successfully.
        - Returns an error if this API is called again after initialization.
      operationId: initializeTables
      requestBody:
        description: The `initializeTables` API initializes all tables in the restaurant.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitializeTablesDTO'
              
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '409':
          description: Tables already initialized
          content:
            application/json:
              schema:
                $ref: '#/components/responses/TablesAlreadyInitializedException'
  /reserveTable:
    post:
      summary: Reserve Tables
      description: |
        The `reserveTable` API in the restaurant for a group of customers.
        
        - This API allows for reserving tables in the restaurant based on the number of customers in a group.
        - If there are more than 4 customers in a group, multiple tables may be booked to accommodate the reservation.
        - Customers in the same group will sit together at the same table(s).
        - The table must not be shared with customers who are in different groups.
        - The position of the tables does not matter, and they do not need to be close to each other.

      operationId: reserveTables
      requestBody:
        description: Reserves tables in the restaurant for a group of customers.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReserveTableDTO'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReserveTableResponse'
        '400':
          description: Not enough tables for all customers
          content:
            application/json:
              schema:
                $ref: '#/components/responses/NotEnoughTablesForAllCustomersException'
        '503':
          description: Tables not initialized
          content:
            application/json:
              schema:
                $ref: '#/components/responses/TablesNotInitializedException'
  /cancelReservation:
    post:
      summary: Cancel Reservation
      description: |
        The `cancelReservation` API allows canceling a reservation in the restaurant.
        
        - This API must be called after initialization.
        - A Booking ID must be provided to identify the reservation to cancel.
        - Upon cancellation, all tables associated with the provided Booking ID will be released and made available for other reservations.
        - If successful, the API returns the number of freed tables for the canceled reservation and the number of remaining tables.
        - Returns an error if the provided Booking ID is not found.
      operationId: cancelReservation
      requestBody:
        description: Cancel Reservation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelReservationDTO'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelReservationResponse'
        '404':
          description: Booking ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/responses/BookingIDNotFoundException'