name: Release

on:
  release:
    types:
      - edited
      - released

jobs:
  Release:

    runs-on: ubuntu-latest

    steps:
    - id: get_version
      name: Get version
      uses: jannemattila/get-version-from-tag@v3

    - name: Display version
      run: |
        VERSION=$(echo "${{ steps.get_version.outputs.version }}")
        echo $VERSION

    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd table-booking-service
        mvn -B package
        echo $VERSION
